[2024-01-16T22:29:15.480+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Stream_Data_1.coinMarket manual__2024-01-16T22:29:02.437594+00:00 [queued]>
[2024-01-16T22:29:15.486+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Stream_Data_1.coinMarket manual__2024-01-16T22:29:02.437594+00:00 [queued]>
[2024-01-16T22:29:15.486+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-16T22:29:15.496+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): coinMarket> on 2024-01-16 22:29:02.437594+00:00
[2024-01-16T22:29:15.500+0000] {standard_task_runner.py:57} INFO - Started process 87 to run task
[2024-01-16T22:29:15.502+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Stream_Data_1', 'coinMarket', 'manual__2024-01-16T22:29:02.437594+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmps_efg7a8']
[2024-01-16T22:29:15.504+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask coinMarket
[2024-01-16T22:29:15.547+0000] {task_command.py:415} INFO - Running <TaskInstance: Stream_Data_1.coinMarket manual__2024-01-16T22:29:02.437594+00:00 [running]> on host 99cc150d5212
[2024-01-16T22:29:15.606+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='me' AIRFLOW_CTX_DAG_ID='Stream_Data_1' AIRFLOW_CTX_TASK_ID='coinMarket' AIRFLOW_CTX_EXECUTION_DATE='2024-01-16T22:29:02.437594+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-16T22:29:02.437594+00:00'
[2024-01-16T22:29:16.145+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kafka_stream.py", line 59, in coinMarket_function
    producer = KafkaProducer(bootstrap_servers=['broker:29092'],max_bloc_ms = 5000)
NameError: name 'KafkaProducer' is not defined
[2024-01-16T22:29:16.152+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Stream_Data_1, task_id=coinMarket, execution_date=20240116T222902, start_date=20240116T222915, end_date=20240116T222916
[2024-01-16T22:29:16.162+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task coinMarket (name 'KafkaProducer' is not defined; 87)
[2024-01-16T22:29:16.196+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-16T22:29:16.214+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
