[2024-01-20T23:30:25.100+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Kafka_Producer_1.coinMarket scheduled__2024-01-20T23:29:22.903828+00:00 [queued]>
[2024-01-20T23:30:25.113+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Kafka_Producer_1.coinMarket scheduled__2024-01-20T23:29:22.903828+00:00 [queued]>
[2024-01-20T23:30:25.114+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-20T23:30:25.144+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): coinMarket> on 2024-01-20 23:29:22.903828+00:00
[2024-01-20T23:30:25.150+0000] {standard_task_runner.py:57} INFO - Started process 1765 to run task
[2024-01-20T23:30:25.154+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Kafka_Producer_1', 'coinMarket', 'scheduled__2024-01-20T23:29:22.903828+00:00', '--job-id', '1473', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpei3qckt3']
[2024-01-20T23:30:25.156+0000] {standard_task_runner.py:85} INFO - Job 1473: Subtask coinMarket
[2024-01-20T23:30:25.244+0000] {task_command.py:415} INFO - Running <TaskInstance: Kafka_Producer_1.coinMarket scheduled__2024-01-20T23:29:22.903828+00:00 [running]> on host 45c5bfab8aa1
[2024-01-20T23:30:25.428+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='me' AIRFLOW_CTX_DAG_ID='Kafka_Producer_1' AIRFLOW_CTX_TASK_ID='coinMarket' AIRFLOW_CTX_EXECUTION_DATE='2024-01-20T23:29:22.903828+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-20T23:29:22.903828+00:00'
[2024-01-20T23:30:25.935+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.19.0.8', 29092)]>: connecting to broker:29092 [('172.19.0.8', 29092) IPv4]
[2024-01-20T23:30:25.936+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-01-20T23:30:25.937+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.19.0.8', 29092)]> returned error 111. Disconnecting.
[2024-01-20T23:30:25.937+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.19.0.8', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-01-20T23:30:25.984+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.19.0.8', 29092)]>: connecting to broker:29092 [('172.19.0.8', 29092) IPv4]
[2024-01-20T23:30:25.985+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.19.0.8', 29092)]> returned error 111. Disconnecting.
[2024-01-20T23:30:25.986+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.19.0.8', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-01-20T23:30:25.987+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kafka_stream.py", line 63, in coinMarket_function
    producer = KafkaProducer(bootstrap_servers=['broker:29092'],max_block_ms = 5000)
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/kafka.py", line 381, in __init__
    client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/client_async.py", line 900, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-01-20T23:30:26.006+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Kafka_Producer_1, task_id=coinMarket, execution_date=20240120T232922, start_date=20240120T233025, end_date=20240120T233026
[2024-01-20T23:30:26.019+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1473 for task coinMarket (NoBrokersAvailable; 1765)
[2024-01-20T23:30:26.051+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-20T23:30:26.071+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
